# Generated by Django 4.1.2 on 2022-11-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Burgerking', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
    ]
