# Generated by Django 4.1.2 on 2022-11-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Burgerking', '0003_alter_details_address_alter_details_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
