# Generated by Django 4.1.2 on 2022-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Burgerking', '0005_login_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
