# Generated by Django 4.1.2 on 2022-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Burgerking', '0007_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order',
            field=models.CharField(max_length=100),
        ),
    ]
