# Generated by Django 4.1.2 on 2022-12-22 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Burgerking', '0015_order_address_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
